# Generated by Django 4.2.3 on 2023-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
