# Generated by Django 4.2.3 on 2023-07-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
