# Generated by Django 4.2.3 on 2023-07-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
    ]
