# Generated by Django 4.2.3 on 2023-07-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
